service: example-app

provider:
  name: aws
  region: eu-central-1

resources:
  Resources:
    FrontPageWebsiteBucket:
      Type: AWS::S3::Bucket
    FrontPageWebsiteBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref FrontPageWebsiteBucket
        PolicyDocument:
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource:
                Fn::Join:
                  - /
                  - - Fn::GetAtt:
                        - FrontPageWebsiteBucket
                        - Arn
                    - '*'
              Principal:
                CanonicalUser:
                  Fn::GetAtt:
                    - FrontPageWebsiteOriginAccessIdentity
                    - S3CanonicalUserId

    FrontPageWebsiteOriginAccessIdentity:
      Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
      Properties:
        CloudFrontOriginAccessIdentityConfig:
          Comment: Origin Access Identity to Access Website Bucket
    FrontPageCloudFront:
      Type: AWS::CloudFront::Distribution
      DependsOn:
        - FrontPageWebsiteBucket
      Properties:
        DistributionConfig:
          Origins:
            - DomainName:
                Fn::GetAtt:
                  - FrontPageWebsiteBucket
                  - DomainName
              Id: S3Origin
              S3OriginConfig:
                OriginAccessIdentity:
                  Fn::Join:
                    - /
                    - - origin-access-identity
                      - cloudfront
                      - !Ref FrontPageWebsiteOriginAccessIdentity
          CustomErrorResponses:
            - ErrorCachingMinTTL: 0
              ErrorCode: 403
              ResponseCode: 200
              ResponsePagePath: /index.html
          DefaultCacheBehavior:
            AllowedMethods:
              - GET
              - HEAD
            Compress: true
            ForwardedValues:
              QueryString: true
              Cookies:
                Forward: none
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
          Comment: personal website
          DefaultRootObject: index.html
          Enabled: true
          HttpVersion: http2
          PriceClass: PriceClass_All
          ViewerCertificate:
            AcmCertificateArn: arn:aws:acm:us-east-1:368241678678:certificate/5a3b28ce-8c67-4e2e-90fb-c6b1cfdc2bf4
            MinimumProtocolVersion: TLSv1.1_2016
            SslSupportMethod: sni-only
          Aliases:
            - christopher.bekos.click

    FrontPageDNSName:
      Type: AWS::Route53::RecordSetGroup
      Properties:
        HostedZoneName: bekos.click.
        RecordSets:
          - Name: christopher.bekos.click
            Type: A
            AliasTarget:
              HostedZoneId: Z2FDTNDATAQYW2 #CloudFront HostedZoneId - always static: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html#cfn-route53-aliastarget-hostedzoneid
              DNSName:
                Fn::GetAtt:
                  - FrontPageCloudFront
                  - DomainName